### ISSUE TITLE
Unneccessary page refresh in certain browsers

### ISSUE THREAD

**Issue by nair66** [nair66/tech-utsav#1]
Unintended Page refresh occurring when : 

1. When page is opened in certain browsers such as chrome, brave.
2. Scrolling fast too much to the top or bottom using browsers mentioned above,  causes an unintended page refresh

**Comment by Ibaqu** [comment]
Add Safari to the list of browsers

**Comment by nair66** [comment]
The overflow-scrolling is a default behavior in many mobile browsers and the **overflow-scrolling** CSS property does not seem to work, hence animations altogether have been disabled on mobiles and tablets.
